name: "monorepo-dev"

x-restart: &default-restart
  restart: unless-stopped

services:
  langflow:
    image: langflowai/langflow:1.2.0
    container_name: langflow_dev
    <<: *default-restart
    env_file: "env/langflow.env"
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    volumes:
      - langflow-data:/app/langflow
      - langflow-config:/app/config
    networks:
      node-network:
        aliases:
          - langflow

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_dev
    <<: *default-restart
    env_file:
      - env/n8n.env
    ports:
      - 5678:5678
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      node-network:
        aliases:
          - n8n

  postgres:
    image: postgres:17
    container_name: postgres_dev
    <<: *default-restart
    env_file: "env/postgres.env"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/data
    networks:
      node-network:
        aliases:
          - postgres
  mongodb:
    image: mongo:8
    container_name: mongo_dev
    <<: *default-restart
    env_file: "env/mongo.env"
    ports:
      - "27017:27017"
    volumes:
     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db
    networks:
      node-network:
        aliases:
          - mongo

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_dev
    <<: *default-restart
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      node-network:
        aliases:
          - qdrant

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_dev
    <<: *default-restart
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      node-network:
        aliases:
          - ollama

volumes:
  n8n-data:
  postgres-data:
  langflow-data:
  langflow-config:
  qdrant-data:
  mongo-data:
  ollama:

networks:
  node-network:
    driver: bridge
