import './global.css';
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

export const metadata = {
  title: 'Welcome to genai-monorepo-template',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
            <head>
        <meta
          name="viewport"
          content="initial-scale=1, width=device-width"
        />
        <link
          rel="icon"
          href="/favicon.ico"
          sizes="any"
        />
      </head>
      <NextIntlClientProvider>
      <body>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
